#!/usr/bin/env python3
"""Regenerate config/detector.yaml (and the package copy) from the DetectorConfig defaults, with inline comments."""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src", "metro_obstacle_detector"))
from metro_obstacle_detector.config import DetectorConfig  # noqa: E402

cfg = DetectorConfig().to_dict()
src = open(os.path.join(ROOT, "src", "metro_obstacle_detector", "metro_obstacle_detector", "config.py"), encoding="utf-8").read()
comments = {m.group(1): m.group(2).strip() for m in re.finditer(r"^\s+(\w+): [^=]+= [^#\n]+#\s*(.*)$", src, re.M)}
lines = ["# Detector parameters (flat mapping). Distances in metres, times in seconds.",
         "# The same file is read by the ROS node (config_file) and the offline evaluator (--config).",
         "# Every key can also be overridden as a ROS parameter of the same name.",
         "# Generated by scripts/gen_config.py from the defaults in config.py; edit either and keep them in sync.", ""]
for k, v in cfg.items():
    c = comments.get(k, "")
    lines.append(f"{k}: {json.dumps(v)}" + (f"  # {c}" if c else ""))
text = "\n".join(lines) + "\n"
for path in (os.path.join(ROOT, "config", "detector.yaml"), os.path.join(ROOT, "src", "metro_obstacle_detector", "config", "detector.yaml")):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
assert DetectorConfig.from_yaml(os.path.join(ROOT, "config", "detector.yaml")).to_dict() == cfg
print(f"wrote {len(cfg)} parameters")
